-- script for VOC handson
USE ROLE ACCOUNTADMIN;
ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'AWS_US';


-- Create Warehouse
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
  WAREHOUSE_SIZE = 'SMALL'
  WAREHOUSE_TYPE = 'STANDARD'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Warehouse for VOC analyze with Cortex LLM';


-- Prepare stages for data, PDFs, and semantic model artifacts.


CREATE DATABASE IF NOT EXISTS VOC_ANALYZE;
CREATE SCHEMA IF NOT EXISTS AIRLINE_SURVEY;
use schema VOC_ANALYZE.AIRLINE_SURVEY;

CREATE OR REPLACE STAGE VOC_ANALYZE.AIRLINE_SURVEY.HANDSON_RESOURCES
    DIRECTORY = (ENABLE = TRUE)
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
    COMMENT = 'Stage for VOC HandsOn';



-- Configure Git integration so we can pull handson assets.
CREATE OR REPLACE API INTEGRATION git_api_integration
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/snow-jp-handson-org/')
  ENABLED = TRUE;

CREATE OR REPLACE GIT REPOSITORY GIT_INTEGRATION_FOR_VOC_ANALYZE_HANDSON
  API_INTEGRATION = git_api_integration
  ORIGIN = 'https://github.com/snow-jp-handson-org/voc_analyze_for_airline.git';

list @GIT_INTEGRATION_FOR_VOC_ANALYZE_HANDSON/branches/main;

COPY FILES INTO @VOC_ANALYZE.AIRLINE_SURVEY.HANDSON_RESOURCES/Data
  FROM @GIT_INTEGRATION_FOR_VOC_ANALYZE_HANDSON/branches/main/Data/
  PATTERN = '.*\\.csv.gz$';


-- アンケートテーブル
CREATE OR REPLACE TABLE VOC_ANALYZE.AIRLINE_SURVEY.SURVEYS (
  SURVEY_ID         NUMBER(38,0) IDENTITY(1,1) PRIMARY KEY COMMENT '内部サロゲートキー',
  FREE_TEXT_COMMENT VARCHAR                         COMMENT '自由記述'
)
COMMENT = '搭乗アンケート';

COPY INTO VOC_ANALYZE.AIRLINE_SURVEY.SURVEYS
FROM '@VOC_ANALYZE.AIRLINE_SURVEY.HANDSON_RESOURCES/Data'
FILE_FORMAT = (TYPE = CSV COMPRESSION = GZIP)
PATTERN = '.*[.]csv[.]gz'
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE NOTEBOOK VOC_ANALYZE_for_Airline
  FROM @GIT_INTEGRATION_FOR_VOC_ANALYZE_HANDSON/branches/main/Notebook
  MAIN_FILE = 'AI SQL for Airline.ipynb'
  QUERY_WAREHOUSE = COMPUTE_WH
  WAREHOUSE = SYSTEM$STREAMLIT_NOTEBOOK_WH;
